Repository kor-jongwon/mobile, pull requests merged in 2023-11, with the labels that each got.

#19 [feature] 1. 센서 등록 페이지 수정 및 서버 연결
  app/src/main/java/com/example/mobile/SensorRegisterActivity.java
  app/src/main/java/com/example/mobile/api_url.java
  app/src/main/res/layout/activity_sensor_register.xml
Labels: rest api, refactory

#22 error 발생 체크
  app/src/main/java/com/example/mobile/SensorRegisterActivity.java
Labels: bug

#24 Make plnat
  app/src/main/java/com/example/mobile/PlantActivity.java
  app/src/main/java/com/example/mobile/PlantDetailActivity.java
  app/src/main/java/com/example/mobile/PlantRegisterRequestHttpURLConnection.java
  app/src/main/java/com/example/mobile/Plant_RegisterList.java
  app/src/main/java/com/example/mobile/PlantsAdapter.java
  app/src/main/java/com/example/mobile/RegisterPlantActivity.java
  app/src/main/java/com/example/mobile/SensorRegisterList.java
  app/src/main/java/com/example/mobile/api_url.java
  app/src/main/res/drawable/rounded_border.xml
  app/src/main/res/layout/activity_plants_detail.xml
  app/src/main/res/layout/activity_plants_list.xml
  app/src/main/res/layout/item_plant.xml
  app/src/main/res/layout/plant_item.xml
  app/src/main/res/layout/plant_register_list.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, android
